# Generated by Django 4.0 on 2024-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
