# Generated by Django 4.0 on 2024-10-06 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_useraddress_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='receiver_name',
            field=models.CharField(max_length=100),
        ),
    ]
