# Generated by Django 4.0 on 2024-10-06 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_remove_userprofile_id_useraddress_receiver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='public_place',
        ),
        migrations.RemoveField(
            model_name='address',
            name='public_place_type',
        ),
    ]
