# Generated by Django 4.0 on 2024-10-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_remove_userprofile_id_userprofile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=2),
        ),
    ]
