# Generated by Django 4.0 on 2024-11-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_alter_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(max_length=250),
        ),
    ]
