# Generated by Django 4.0 on 2024-06-02 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('ads', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_questions', to='questions.question'),
        ),
    ]
