# Generated by Django 4.0 on 2024-06-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_announcement_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='condition',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('USADO', 'Usado'), ('DANIFICADO', 'Danificado'), ('SEMINOVO', 'Seminovo'), ('ANTIGO - RARO', 'Antigo - Raro'), ('ANTIGO - COLEÇÃO', 'Antigo - Coleção'), ('ENCADERNAÇÃO ESPECIAL', 'Encadernação Especial')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('DISABLE', 'disable'), ('ACTIVATED', 'activated')], default='disable', max_length=10),
        ),
    ]
