# Generated by Django 4.0 on 2024-09-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ads', '0004_alter_announcement_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='study_area',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_user_ads', to='auth.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='study_area',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_user_product', to='auth.user'),
        ),
    ]
