# Generated by Django 4.0 on 2024-09-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ads', '0005_remove_announcement_study_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_user_ads', to='auth.user'),
        ),
    ]
