# Generated by Django 4.0 on 2024-09-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_announcement_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='question',
        ),
    ]
