# Generated by Django 4.0 on 2024-11-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_reply'),
        ('ads', '0007_remove_announcement_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_questions', to='questions.question'),
        ),
    ]
