# Generated by Django 4.0 on 2024-11-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_announcement_quantity_announcement_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
