# Generated by Django 4.0 on 2024-11-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('DISABLE', 'disable'), ('ACTIVATED', 'activated')], default='activated', max_length=10),
        ),
    ]
