# Generated by Django 4.0 on 2024-05-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('study_area', models.CharField(db_index=True, max_length=200)),
                ('condition', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('danificado', 'Danificado'), ('seminovo', 'Seminovo'), ('antigo - raro', 'Antigo - Raro'), ('antigo - coleção', 'Antigo - Coleção'), ('encadernação especial', 'Encadernação Especial')], default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='bookstore.product')),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'title')},
            },
        ),
    ]
