# Generated by Django 4.0 on 2024-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('disable', 'Disabled'), ('activated', 'Activated')], default='disable', max_length=10),
        ),
    ]
