# Generated by Django 4.0 on 2024-05-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_questions', to='bookstore.question'),
        ),
    ]
