# Generated by Django 4.0 on 2024-05-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_announcement_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='complement',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='nickname',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='public_place',
        ),
        migrations.RemoveField(
            model_name='address',
            name='number',
        ),
        migrations.AddField(
            model_name='address',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='address',
            name='public_place_type',
            field=models.CharField(default='default_type', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='BA', max_length=2),
        ),
    ]
