# Generated by Django 4.0 on 2024-05-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_product_seller'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='question',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='question',
            name='client',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
