# Generated by Django 4.0 on 2024-09-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_product_seller_alter_userprofile_address'),
        ('bookstore', '0011_alter_product_index_together_remove_product_seller_and_more'),
    ]

    operations = [
    ]
