# Generated by Django 4.0 on 2024-10-09 00:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_announcement_question'),
        ('cartitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='quantity',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='itemcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='ads.product'),
        ),
    ]
