# Generated by Django 4.0 on 2024-11-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_announcement_quantity_announcement_question'),
        ('cartitem', '0002_itemcart_quantity_alter_itemcart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='product',
        ),
        migrations.AddField(
            model_name='itemcart',
            name='announcement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.announcement'),
        ),
    ]
