# Generated by Django 4.0 on 2024-11-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_announcement_status'),
        ('cartitem', '0003_remove_itemcart_product_itemcart_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='announcement',
        ),
        migrations.AddField(
            model_name='itemcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='ads.product'),
            preserve_default=False,
        ),
    ]
