# Generated by Django 4.0 on 2024-11-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_announcement_status'),
        ('cart', '0003_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, to='ads.Product'),
        ),
    ]
