# Generated by Django 4.0 on 2024-11-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0008_announcement_quantity_announcement_question'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.announcement')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buyer', to='auth.user')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to='auth.user')),
            ],
        ),
    ]
