# Generated by Django 4.0 on 2024-11-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_alter_address_street'),
        ('orders', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auths.useraddress'),
            preserve_default=False,
        ),
    ]
